### ISSUE TITLE
finviz map crawling issue

### ISSUE THREAD

**Issue by moonuckjoo** [Nagnero/Finance-Trading-Assistance#5]
https://finviz.com/map.ashx
해외증시란에 finviz 사이트에 있는 map형태를 가져오려고 하였으나 js형태로 만들어져 있어서 crawling에 어려움을 느낌.

**Comment by Nagnero** [comment]
대안으로 국내 주식의 map을 만들어보려 하였으나 zum financial에 이미 존재

대신 중요한 지수들을 출력하는 방향으로 수정함
